# Site settings
title: Howdy!
email: howdy@awhitty.me
description: "Austin Whittier is a goof studying Computer Science. He likes music, bicycles, coffee, and Google site descriptions. Hi."
baseurl: ""
url: "http://www.awhitty.me"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
